### ISSUE TITLE
Playtest: Get good VR camera angle

### ISSUE THREAD

**Issue by Schroth94** [VengeanceRising/VengeanceRising#89]
-player rotation on level start should fit our player starts
-bag must be reachable
-subtitles must look good
-fade in/out for level transitions must work

**Comment by rodsonchue** [comment]
Inconsistent subtitles is mostly caused by poor vr calibration. When a player is using the headset, make sure to calibrate for him. Several play tests have shown that the vr camera mount should be placed further away from the player (either by moving the monitor further back, or making the player sit further back

**Comment by rodsonchue** [comment]
All not solved things have their own issues. See #73 and #77.
